#!/bin/sh

#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=Junos Admin
# PLUGIN_CATEGORY=SECR
# PLUGIN_DATE=2024-09-19
# PLUGIN_DESC=Discover secret sensitive data
# PLUGIN_NAME=secrets
# PLUGIN_REQUIRED_TESTS=
# PLUGIN_PACKAGE=
# PLUGIN_VERSION=0.1.0
#-----------------------------------------------------
#
#########################################################################

get_secrets() {
    #start
    LogText "Test: Discover secret sensitive data in text files."
    # TODO: widen scope of search

    # define some constant
    IFS_OLD=$IFS
    IFS=$'\n'
    secrets=$(${FINDBINARY} / -not -path '/proc/*' -not -path '/junosproc/*' -type f -exec ${GREPBINARY} -m1 -I "PRIVATE KEY" {} /dev/null \;)
    count=0

    for _item in ${secrets};
    do
        Report "secret[]=${_item}"
        count=$((count+1))
    done

    Report "secret_count[]=${count}"

    IFS=$IFS_OLD
}

#########################################################################
#
    # Add custom section to screen output
    InsertSection "SECRET ENTRIES"
#
#################################################################################
#
    # Test        : SECR-0001
    # Description : 

    # Register our first custom test
    # We consider no network connection needed
    Register --test-no SECR-0001 --weight L --network NO --description "Collect list locations that might have secret sensitive data"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Obtain secrets" --result OK --color GREEN
        get_secrets;
    fi
#
#################################################################################
#

# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#EOF