#!/bin/sh

#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=Junos Admin
# PLUGIN_CATEGORY=BINS
# PLUGIN_DATE=2024-09-03
# PLUGIN_DESC=A test to find all binary files
# PLUGIN_NAME=check_all_binaries
# PLUGIN_REQUIRED_TESTS=
# PLUGIN_PACKAGE=
# PLUGIN_REQUIRED_TESTS=
# PLUGIN_VERSION=0.1.0
#-----------------------------------------------------
#
#########################################################################

# Make this global for reuse in other tests
BIN_FILES=''

get_all_bins() {
    # define some constant
    IFS_OLD=$IFS
    IFS=$'\n' 
    #start
    LogText "Test: Obtain all binary file names"
    bin_files=$(${FINDBINARY} / -type f -exec file -i '{}' \; | ${GREPBINARY} 'x-executable; charset=binary' | ${CUTBINARY}  -d':' -f 1)
    BIN_FILES=${bin_files}
    count=$(echo -e "${bin_files}" | wc -l) 

    Report "bin_files_count[]=$count"

    for each_file in ${bin_files};
    do
        Report "bin_files[]=${each_file}"
    done
    IFS=$IFS_OLD
}

#########################################################################
#
    # Add custom section to screen output
    InsertSection "BINARIES"
#
#################################################################################
#
    # Test        : BINS-0001
    # Description : We show some lines on the screen

    # Register our first custom test
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no BINS-0001 --weight L --network NO --description "A test to find all binary files"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Finding binary file" --result OK --color GREEN
        get_all_bins;
    fi
#
#################################################################################
#

# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#EOF