#!/bin/sh

#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=Junos Admin
# PLUGIN_CATEGORY=BINS
# PLUGIN_DATE=2024-09-03
# PLUGIN_DESC=A test to find all sharedlib file libs
# PLUGIN_NAME=check_all_sharedlib_libs
# PLUGIN_REQUIRED_TESTS=check_0_all_sharedlibs
# PLUGIN_PACKAGE=
# PLUGIN_VERSION=0.1.0
#-----------------------------------------------------
#
#########################################################################

get_all_lib_libs() {
    # define some constant
    IFS_OLD=$IFS
    IFS=$'\n'
    LDDBIN='ldd' # TODO: make global from functions
    #start
    LogText "Test: Obtain path and lib file name for all libs"
    lib_file_libs=${LIB_FILES:-}

    for each_file in ${lib_file_libs};
    do
        display_str=$(${LDDBIN} ${each_file} | ${AWKBINARY}  -F' ' '/^\t/ { printf("%s %s\n", "'${each_file}'", $3) }')
        if [ "${display_str}" != '' ]; then
            Report "lib_file_libs[]=$display_str"
        fi
    done
    IFS=$IFS_OLD
}

#########################################################################
#
    # Add custom section to screen output
    InsertSection "BINARIES"
#
#################################################################################
#
    # Test        : BINS-0004
    # Description : We show some lines on the screen
    # BIN_FILES must have been populated in other test.
    if [ "${LIB_FILES:-''}" != '' ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no BINS-0004 --preqs-met ${PREQS_MET} --weight L --network NO --description "A test to list sharedlib file libs"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Finding sharedlib file libs" --result OK --color GREEN
        get_all_lib_libs;
    fi
#
#################################################################################
#

# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#EOF