#!/bin/sh

#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=Junos Admin
# PLUGIN_CATEGORY=INSE
# PLUGIN_DATE=2024-09-03
# PLUGIN_DESC=List running network daemons
# PLUGIN_NAME=daemons
# PLUGIN_REQUIRED_TESTS=
# PLUGIN_PACKAGE=
# PLUGIN_VERSION=0.1.0
#-----------------------------------------------------
#
#########################################################################

list_daemons() {
    #start
    LogText "Test: Obtain list of running network daemons"

    # define some constant
    IFS_OLD=$IFS
    IFS=$'\n'
    daemon_services=''

    for each_service in ${daemon_services};
    do
        Report "daemon_services[]=$each_service"
    done
    IFS=$IFS_OLD
}

#########################################################################
#
    # Add custom section to screen output
    InsertSection "INETD ENTRIES"
#
#################################################################################
#
    # Test        : INSE-CUST-0002
    # Description : 

    # Register our first custom test
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no INSE-CUST-0002 --weight L --network NO --description "Collect list of running daemons"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Obtain daemon services" --result OK --color GREEN
        extract_inetd_fields;
    fi
#
#################################################################################
#

# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#EOF