#!/bin/sh

#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=Junos Admin
# PLUGIN_CATEGORY=SUID
# PLUGIN_DATE=2024-09-03
# PLUGIN_DESC=A test for find suid file
# PLUGIN_NAME=check_suid_file
# PLUGIN_REQUIRED_TESTS=
# PLUGIN_PACKAGE=
# PLUGIN_VERSION=0.1.0
#-----------------------------------------------------
#
#########################################################################

check_suid_file() {
    # define some constant
    IFS_OLD=$IFS
    IFS=$'\n' 
    #start
    LogText "Test: Obtain suid file name"
    suid_files=$(find / -perm 2000 -o -perm -4000 -type f -exec ls -la {} 2>/dev/null \;)
    for each_file in ${suid_files};
    do
        Report "suid_file[]=$each_file"
    done
    IFS=$IFS_OLD
}

check_guid_file() {
    # define some constant
    IFS_OLD=$IFS
    IFS=$'\n' 
    #start
    LogText "Test:obtain guid file name"
    guid_files=$(find / -perm 2000 -o -perm -4000 -type f -exec ls -la {} 2>/dev/null \;)
    for each_file in ${guid_files};
    do
        Report "guid_file[]=$each_file"
    done
    IFS=$IFS_OLD
}
#########################################################################
#
    # Add custom section to screen output
    InsertSection "SUID"
#
#################################################################################
#
    # Test        : SUID-0001
    # Description : We show some lines on the screen

    # Register our first custom test
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no SUID-0001 --weight L --network NO --description "A test for find suid file"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Finding hidden file" --result OK --color GREEN
        check_suid_file;
    fi
#
#################################################################################
#

# Wait for keypress (unless --quick is being used)
WaitForKeyPress

#EOF