#!/bin/sh

#########################################################################
#
#    * DO NOT REMOVE *
#-----------------------------------------------------
# PLUGIN_AUTHOR=Junos Admin
# PLUGIN_CATEGORY=BINS
# PLUGIN_DATE=2024-09-08
# PLUGIN_DESC=Discover all shell scripts
# PLUGIN_NAME=check_all_sh_scripts
# PLUGIN_PACKAGE=
# PLUGIN_REQUIRED_TESTS=
# PLUGIN_VERSION=0.1.0
#-----------------------------------------------------
#
#########################################################################

# Make this global for reuse in other tests
SCRIPT_FILES=''

get_all_sh_scripts() {
    # define some constant
    IFS_OLD=$IFS
    IFS=$'\n' 
    #start
    LogText "Test: Obtain all shell scripts"
    script_files=$(${FINDBINARY} / -not -path '/proc/*' -type f -exec ${GREPBINARY} -Iq . {} \; -exec ${HEADBINARY} -1 {} /dev/null \; | ${AWKBINARY} '/sh/ { print file } { file = $0 } ' | ${CUTBINARY} -d' ' -f2 | ${GREPBINARY} -v '/dev/null' | ${XARGSBINARY} -I {} ${FILEBINARY} {} | ${GREPBINARY} script)
    SCRIPT_FILES="${libbin_files}"
    count=$(echo -e "${script_files}" | wc -l) 

    Report "script_files_count[]=$count"

    for each_file in ${script_files};
    do
        Report "script_files[]=$each_file"
    done
    IFS=$IFS_OLD
}

#########################################################################
#
    # Add custom section to screen output
    InsertSection "SHELL SCRIPTS"
#
#################################################################################
#
    # Test        : BINS-0005
    # Description : We show some lines on the screen
    if [ "${SCRIPT_FILES:-''}" != '' ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    # We consider it to be a lightweight test (no heavy IO, or long searches), no network connection needed
    Register --test-no BINS-0005 --weight L --network NO --description "A test to find all script files"
    if [ ${SKIPTEST} -eq 0 ]; then
        # The Display function makes it easy to show something on screen, with colors.
        # --indent  defines amount of spaces
        # --text    text to be displayed on screen
        # --result  text at end of line
        # --color   color of result text
        Display --indent 2 --text "- Finding shell script file" --result OK --color GREEN
        get_all_sh_scripts;
    fi
#
#################################################################################
#

#EOF